version: "3.8"

services:
  server:
    ports:
      - "5000:8080"
  client:
    ports:
    - "5001:3000"
  proxy:
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:80"
    restart: on-failure