version: "3.8"

services:
  server:
    image: server
    build: 
      context: .
      dockerfile: server/Dockerfile
  client:
    image: client
    build: 
      context: ./client
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline

